### ISSUE TITLE
Color differentiation

### ISSUE THREAD

**Issue by manez** [mjordan/islandora_repository_reports#17]
This is a pretty mild issue, since it can be easily resolved by just clicking "Go" again and rolling new colors, but it seems that once you get past 5 or 6 different things in one chart, the colors can start to collide a little:

![image](https://user-images.githubusercontent.com/2371345/81810874-1c8da080-94fa-11ea-9f17-aca6e9471a28.png)

![image](https://user-images.githubusercontent.com/2371345/81810898-257e7200-94fa-11ea-9d6c-6970fe797b16.png)

**Comment by mjordan** [comment]
Since colors for pie charts are randomly generated, we're at the mercy of the Random Gods, who don't guarantee a distinct color pallate. But, we might be able to provide an option to use a predetermined list of colors that are distinguishable enough from their neighbors in the chart to avoid the effect you are describing. In other words, if you want random colors, you take a chance to getting whacked by the Random Gods' Random Hammer, but if you choose the predermined list of colors, you would be safe from the Random Hammer. Deluxe version of the predetermined choice would be to provide multiple color schemes and let the user choose their favorite.

**Comment by mjordan** [comment]
@manez my previous comment was pretty cryptic, so using less flamboyant language I'd like to propose that we add an admin option to use random colors in pie charts (like now) or to use a predetermined pallate. We can make sure the predetermined one has lots of variation. How does that sound?

**Comment by manez** [comment]
@mjordan an excellent way to evade the wrath of the Random Gods 😄

**Comment by mjordan** [comment]
Now there is an option to randomize colors in pie charts or not. To toggle it, go to Admin > Configuration > Islandora > Islandora Repository Reports.

**Comment by manez** [comment]
Tested it out. Works well, and no more half-lime-green charts (uness I feel like rolling the dice) 🎲

**Comment by mjordan** [comment]
Thanks!
